# Site
name: "onpremisys"
title: "onpremisys"
description: "Sharing thoughts on running an on-premise Microsoft oriented hosting platform."
logo: 'assets/images/on-prem.png'
favicon: 'assets/images/on-prem.png'
baseurl: ''
url: "https://onpremisys.nl"
google_analytics: 'UA-142507058-1'
disqus: 'onpremisys'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  broovers:
    name: Bas Roovers
    display_name: Bas Roovers
    description: 'Author of onpremisys and working with in IT for over 10 years. Loves good discussions and new technologies.'
    avatar: 'assets/images/avatar-broovers.jpg'
    email: mail@basroovers.nl
    twitter: https://twitter.com/bas_roovers
  mvosslamber:
    name: Marcel Vosslamber
    display_name: Marcel Vosslamber
    avatar: 'assets/images/avatar.png'
    twitter: https://twitter.com/mavel_

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
